spring:
  datasource:
    url: jdbc:h2:~/jinhyung;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    name: sa
    driver-class-name: org.h2.Driver
  freemarker:
    cache: false
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    username: hjhng125@gmail.com
    password: 1q2w3e4r1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080